### ISSUE TITLE
Update readme with new features and setup

### ISSUE THREAD

**Issue by jonnybluesman** [King-s-Knowledge-Graph-Lab/revont#2]
We shall revise the readme and include all details for: (i) setup; (ii) reproducibility of the experiments; (iii) and instructions of use besides the article.

**Comment by jonnybluesman** [comment]
Update: This also include the new title of this work

**Comment by dignityc** [comment]
Update the prerequisite to introduce pip installment with 'requirements.txt' and add the instruction to introduce how to use '.ipynb' file on the Colab notebook.

The new title will be updated after submitting revised manuscript.
