### ISSUE TITLE
Clean artefacts and revise structure

### ISSUE THREAD

**Issue by jonnybluesman** [King-s-Knowledge-Graph-Lab/revont#3]
There are still temporary files and artefacts from vscode, dumps, etc. Also, we shall revise the repo structure so that we can link relevant files from outside the project.

**Comment by jonnybluesman** [comment]
These include:

- `DS_Store` files, please include them in the .gitignore
- `.vscode/` folder, same as above
- `__pycache__` folders, same as above

**Comment by dignityc** [comment]
Update .gitignore and clean-up cache files
